### ISSUE TITLE
Search() function Blocks LFG Browser when Listing.

### ISSUE THREAD

**Issue by Shelfen** [gk646/GearScoreClassic#11]
This Addon blocks the Search function for LFG in SoD & Fresh

> 2x [ADDON_ACTION_BLOCKED] AddOn 'GearScoreClassic+' tried to call the protected function 'Search()'.
> [string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
> [string "=[C]"]: in function `Search'
> [string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua"]:250: in function `LFGBrowse_DoSearch'
> [string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua"]:189: in function `SearchActiveEntry'
> [string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_ParentFrame.lua"]:95: in function `LFGParentFrame_SearchActiveEntry'
> [string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Listing.lua"]:77: in function <...pFinder_VanillaStyle/Blizzard_LFGVanilla_Listing.lua:54>
> 
> Locals:
> _ = Frame {
> }
> event = "ADDON_ACTION_BLOCKED"
> events = <table> {
> }

**Comment by gk646** [comment]
Hey,
thanks for the report. Is there any more error logs you can show me?
I dont really see which function is calling this protected function and when.

**Comment by Shelfen** [comment]
Unfortunately i do not have any more logs than that i believe, tried it with the new update you threw out with the potential fix unfortunately didn't fix the problem, tried now with only BugSack and GearScoreClassic+ with. same result.

Still the same error, seems quote didn't work well in the other post, throwing it in code block this time.

```
[ADDON_ACTION_BLOCKED] AddOn 'GearScoreClassic+' tried to call the protected function 'Search()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Search'
[string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua"]:250: in function `LFGBrowse_DoSearch'
[string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua"]:189: in function `SearchActiveEntry'
[string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_ParentFrame.lua"]:95: in function `LFGParentFrame_SearchActiveEntry'
[string "@Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Listing.lua"]:77: in function <...pFinder_VanillaStyle/Blizzard_LFGVanilla_Listing.lua:54>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
```

**Comment by Shelfen** [comment]
What the sorry i was screwing around with the dropdown menu there need to reopen, oof.

**Comment by gk646** [comment]
Sadly i cant try it out myself as i have no subscription. And i dont really see how any method iam calling triggers a Search() and this callstack.

**Comment by Shelfen** [comment]
Thats to bad, understandable that you dont have the time or subscription to check deeper into the issue, maybe someone can jump into this issue as a fork or throw you the fix sometime in the future.

**Comment by gk646** [comment]
Well no need for a fork. Ill happily merge fixes.
But you can just switch to the other addon:
https://github.com/gk646/GearScoreClassic/issues/10#issuecomment-2501598922

Thanks for using GearScoreClassic+!

**Comment by Shelfen** [comment]
Seems Rune Reminder had the same problem as your addon, he wrote this in the patch notes:

```
v 1.3.5
----------
* Updated dropdowns to use LibUIDropDownMenu, to prevent taint issues
```

Maybe thats something to look at, not sure if you know what to do with this.

Else i will try to use the other addon, but ive grown to like your addon :P

**Comment by gk646** [comment]
Ill take a look.
Thanks, hearing that motivates me :).
Feel free to tell me the updated maximum gearscore or input it yourself to get updated color coding!

**Comment by gk646** [comment]
Can you try to set:
/console scriptErrors 1
Or is it already set?

Also try this fix:
Replace the SetScript with HookScript in line 5 of Main.lua (with a text editor)
Save and reload reload the UI.
If that doesnt fix it i dont really know...

**Comment by Shelfen** [comment]
Oh, here is something new i found online to allow Taint.log file to track things, seems create frame is causing problems. on Line 2 in Main.lua

```
12/5 05:57:39.421  Global variable frame tainted by GearScoreClassic+ - Interface/AddOns/GearScoreClassic+/Main.lua:2
12/5 05:57:39.421  Execution tainted by GearScoreClassic+ while reading frame - Interface/AddOns/Blizzard_SharedXML/Classic/UIDropDownMenu.lua:561
12/5 05:57:39.421      UIDropDownMenu_AddButton()
12/5 05:57:39.421      Interface/AddOns/Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua:886 initFunction()
12/5 05:57:39.421      Interface/AddOns/Blizzard_SharedXML/Classic/UIDropDownMenu.lua:84 UIDropDownMenu_Initialize()
12/5 05:57:39.421      Interface/AddOns/Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua:179 LFGBrowseFrame:SearchActiveEntry()
12/5 05:57:39.421      Interface/AddOns/Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_ParentFrame.lua:95 LFGParentFrame_SearchActiveEntry()
12/5 05:57:39.421      Interface/AddOns/Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Listing.lua:77
12/5 05:57:39.421  LFGListingActivityView_InitActivityButton()
12/5 05:57:39.421  An action was blocked because of taint from GearScoreClassic+ - Search()
12/5 05:57:39.421      Interface/AddOns/Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua:250 LFGBrowse_DoSearch()
12/5 05:57:39.421      Interface/AddOns/Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Browse.lua:189 LFGBrowseFrame:SearchActiveEntry()
12/5 05:57:39.421      Interface/AddOns/Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_ParentFrame.lua:95 LFGParentFrame_SearchActiveEntry()
12/5 05:57:39.421      Interface/AddOns/Blizzard_GroupFinder_VanillaStyle/Blizzard_LFGVanilla_Listing.lua:77
```

**Comment by Shelfen** [comment]
Seems i managed to fix it by edditing the variable «frame» -> «f» since «frame» is likely used by blizzard, works now without an error

```
f = CreateFrame("Frame")
f:RegisterEvent("PLAYER_EQUIPMENT_CHANGED")
f:RegisterEvent("INSPECT_READY")
f:SetScript("OnEvent", function(self, event, inspectGUID)
```

Will poke you about the max gearscore in AQ40 Phase once items start popping out

**Comment by gk646** [comment]
Great work, thanks!
Do you want to submit a pull request or should i just add it?
This taint thing is really a interesting but also very intransparent...
Also you can just edit the MAX_SCORE for yourself in the first lines of GearScore.lua

**Comment by Shelfen** [comment]
You can just add it yourself i think, im not used to Github that way so its enough for me to suggest the fix ;)

Also its likely best as you say it that its better to keep the max gearscore as is and edit it yourself.

**Comment by gk646** [comment]
Well its meant for SOD current phase. Most people dont know that they could easily edit it like this.
I meant it in a way that your now empowered to edit Plugins yourself and wanted to make sure you know what to change so it always works for you (regardless of the update).
I had a lot of fun back then making my two plugins.
I bet you could do it aswell. I would gladly check those out!
