### ISSUE TITLE
Error when mouseovering Ammunition in inventory/on vendor

### ISSUE THREAD

**Issue by Stormseer** [gk646/GearScoreClassic#4]
31x GearScoreClassic+/GearScoreCalc.lua:144: attempt to index field '?' (a nil value)
[string "@GearScoreClassic+/GearScoreCalc.lua"]:144: in function <GearScoreClassic+/GearScoreCalc.lua:139>
[string "@GearScoreClassic+/GearScoreCalc.lua"]:280: in function <GearScoreClassic+/GearScoreCalc.lua:277>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetAction'
[string "@Bartender4/libs/LibActionButton-1.0-110/LibActionButton-1.0.lua"]:2261: in function `SetTooltip'
[string "@Bartender4/libs/LibActionButton-1.0-110/LibActionButton-1.0.lua"]:1968: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1961>
[string "@Bartender4/libs/LibActionButton-1.0-110/LibActionButton-1.0.lua"]:1046: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1044>

Locals:
itemLink = "|cffffffff|Hitem:11285::::::::40:::::::::|h[Jagged Arrow]|h|r"
_ = "Jagged Arrow"
_ = "|cffffffff|Hitem:11285::::::::40:::::::::|h[Jagged Arrow]|h|r"
itemRarity = 1
itemLevel = 45
_ = 40
_ = "Projectile"
_ = "Arrow"
_ = 200
itemEquipLoc = "INVTYPE_AMMO"
(*temporary) = nil
(*temporary) = "INVTYPE_AMMO"
(*temporary) = 135661
(*temporary) = 2
(*temporary) = 6
(*temporary) = 2
(*temporary) = 0
(*temporary) = "attempt to index field '?' (a nil value)"
itemTypeInfo = <table> {
 INVTYPE_RANGEDRIGHT = <table> {
 }
 INVTYPE_SHIELD = <table> {
 }
 INVTYPE_WEAPONOFFHAND = <table> {
 }
 INVTYPE_RANGED = <table> {
 }
 INVTYPE_WEAPON = <table> {
 }
 INVTYPE_2HWEAPON = <table> {
 }
 INVTYPE_WRIST = <table> {
 }
 INVTYPE_TRINKET = <table> {
 }
 INVTYPE_NECK = <table> {
 }
 INVTYPE_CLOAK = <table> {
 }
 INVTYPE_BODY = <table> {
 }
 INVTYPE_THROWN = <table> {
 }
 INVTYPE_HOLDABLE = <table> {
 }
 INVTYPE_TABARD = <table> {
 }
 INVTYPE_LEGS = <table> {
 }
 INVTYPE_ROBE = <table> {
 }
 INVTYPE_FEET = <table> {
 }
 INVTYPE_FINGER = <table> {
 }
 INVTYPE_WAIST = <table> {
 }
 INVTYPE_HAND = <table> {
 }
 INVTYPE_RELIC = <table> {
 }
 INVTYPE_CHEST = <table> {
 }
 INVTYPE_SHOULDER = <table> {
 }
 INVTYPE_HEAD = <table> {
 }
 INVTYPE_WEAPONMAINHAND = <table> {
 }
}
rarityModifiers = <table> {
 0 = 3.500000
 2 = 2.500000
 3 = 1.760000
 1 = 3
 4 = 1.600000
 5 = 1.400000
}
GetEnchantIDFromItemLink = <function> defined @GearScoreClassic+/GearScoreCalc.lua:133
GS_ENCHANT_MODIFIER = 1.050000
GLOBAL_SCALE = 1.700000

**Comment by gk646** [comment]
Thank you. Yes this is a known issue because its equipable but i didnt make an entry for it in the scaling list. 
For now just disable errors by pasting this in your chat: /console scriptErrors 0
It will be fixed in the next update along with hunter ranged weapons not getting the correct score.

**Comment by gk646** [comment]
Uploaded a new update that fixes this issue.
