### ISSUE TITLE
Hunter One-hand GS calculation missing

### ISSUE THREAD

**Issue by TormDeltest** [gk646/GearScoreClassic#5]
Hello, I have been reviewing the code and I noticed an issue with Custom rules for specific classes section (line 143). It focuses on Hunters for obvious reasons. You have special rules for all types of weapons except for One-hand weapons. Therefore One-hand weapon has double gearscore than Main-hand weapon.

Adding this code to line 148 fixed the issue.

        elseif itemEquipLoc == "INVTYPE_WEAPON" then
            return slotModifier  - 0.5

**Comment by TormDeltest** [comment]
On the similar note: Item's GS value on tooltip is not adjusted for hunters. It is calculated as if any other classes and is not reflecting the Custom rules for specific classes.

**Comment by gk646** [comment]
Yes, this is a nice find and i will fix it.
As for the second thing: What you could do is apply the custom rules based on the players class sure.
But then a wand would have more gs if a hunter looks at it vs when a priest looks at it (which isnt really a problem)
I guess ill do that sure. 
Thank you!

**Comment by gk646** [comment]
I wanna note that this was just a on the fly decision to reduce melee scaling in favor of ranged weapon scaling. If you think something else applies better feel free to submit a pr or share your opinion here.
I never played a hunter ;)...

**Comment by TormDeltest** [comment]
I would say the GS increase for Ranged Weapons for Hunters and lowering the GS for melee weapons was a good ideas. But now with the rise of the Melee Hunters I'm not so sure anymore. Melee Hunters are basically Rogues. So they value their melee weapons more than Ranged.  

The addon as far as I can say cannot differentiate between Melee Hunter and Range Hunter unless you add some kind of check like what Runes the Hunter is using or whether they are spec'ed into Savage Strikes talents (it is a Melee Hunter giveaway). 

And regarding the Hunters and Wands, I don't think too many Hunters will be looking at Wands. And argument that they will see different GS for Wand than other players? Well Hunters already see different GS for Weapons as they scale differently for them. I would go for it.

**Comment by TormDeltest** [comment]
I downloaded the update and I can confirm the GS shows correctly now for all types of weapons. And Tooltip GS info contains correct GS value for Hunters! :)
