### ISSUE TITLE
Getting an error in BG's

### ISSUE THREAD

**Issue by Shoelive** [gk646/GearScoreClassic#8]
Heya, just trying to help and report feedback. Got this in a WSG bg:

7x [ADDON_ACTION_BLOCKED] AddOn 'GearScoreClassic+' tried to call the protected function 'CheckInteractDistance()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CheckInteractDistance'
[string "@GearScoreClassic+/Main.lua"]:37: in function <GearScoreClassic+/Main.lua:27>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by gk646** [comment]
Thanks for the report,
 ive seen this a couple times myself. Ill check the usage of the function and try to fix it.

**Comment by Translitdk** [comment]
> Thanks for the report, ive seen this a couple times myself. Ill check the usage of the function and try to fix it.

Adding `not InCombatLockdown()` check in the hook function of main lua fixes it, since it is protected to call in the combat

[warcraft.wiki.gg](https://warcraft.wiki.gg/wiki/API_CheckInteractDistance)

![](https://i.imgur.com/j4K32Ab.png)

**Comment by gk646** [comment]
Thanks ill patch it
