### ISSUE TITLE
Multiple entries of GearScore on Tooltip

### ISSUE THREAD

**Issue by beldense** [gk646/GearScoreClassic#9]
Image: 
![image](https://github.com/user-attachments/assets/131b8aa5-afd0-4d1f-8751-4ac9e48018ae)

![image](https://github.com/user-attachments/assets/1c7ced2c-58b2-4d5d-809f-51e1ad8d3b6e)

Happens sometimes when you hover over players...

**Comment by gk646** [comment]
Thanks for the report!
Ive seen this before. Usually it was very rare. Is this a consistens issue? Also it should go away if you rehover over a player.
